---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: realtimeapp
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./realtimeapp
  prune: true
  healthChecks:
    - kind: Deployment
      name: "realtimeapp"
      namespace: realtimeapp
  sourceRef:
    kind: GitRepository
    name: k8s-common
  validation: client
  dependsOn:
    - name: k8s-common

