---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: akv2k8s
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./akv2k8s
  prune: true
  healthChecks:
    - kind: Deployment
      name: "akv2k8s-controller.akv2k8s"
  sourceRef:
    kind: GitRepository
    name: k8s-common
  validation: client

