---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: k8s-secrets
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-common
  validation: client
  healthChecks:
    - kind: Secret
      name: cftoken
      namespace: flux-system
  dependsOn:
    - name: akv2k8s

