---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: akv2k8s
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./akv2k8s
  prune: true
  health-check: "Deployment/akv2k8s-controller.akv2k8s"
  health-check-timeout: 2m
  sourceRef:
    kind: GitRepository
    name: k8s-common
  validation: client

